services:
  bridge-svelte:
    container_name: bridge-svelte
    image: bridge-svelte:dev
    build:
      target: dev
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/home/bridgeuser/app         
    restart: unless-stopped    
    stdin_open: true
    tty: true
    ports:
      - "3008:3001"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge



