/**
 * Subscription Flow Tests
 *
 * Tests real plan selection and switching flows using the test data API
 * to create/delete plans and set tenant plans directly.
 *
 * Unlike subscription-plans.spec.ts (which uses API mocking), these tests
 * hit the real API to verify the end-to-end UX.
 *
 * Test scenarios:
 * 1. Select a free plan via the PlanSelector UI
 * 2. Switch from one plan to another via the UI
 * 3. (Optional) Stripe checkout is triggered for a paid plan when Stripe is configured
 */

import { test, expect } from '../../fixtures/auth';
import { MED_TIMEOUT, LONG_TIMEOUT } from '../../fixtures/timeouts';

// Keys generated by Stripe test mode — skip Stripe tests if not set
const STRIPE_TEST_PK = process.env.STRIPE_TEST_PK || '';
const STRIPE_TEST_SK = process.env.STRIPE_TEST_SK || '';
const hasStripeKeys = !!STRIPE_TEST_PK && !!STRIPE_TEST_SK;

test.describe('Subscription Flows', () => {
  test('select a free plan via PlanSelector UI', async ({
    authenticatedPage,
    testUser,
    testDataClient,
  }) => {
    const page = authenticatedPage;
    const planKey = `free-e2e-${Date.now()}`;

    try {
      // Create a free plan via the API
      await testDataClient.createPlan({
        key: planKey,
        name: 'Free E2E',
        description: 'Free plan created by E2E test',
        prices: [{ amount: 0, currency: 'USD', recurrenceInterval: 'month' }],
      });

      await page.goto('/subscription');
      await page.waitForURL('**/subscription**', { timeout: MED_TIMEOUT });
      await page.waitForLoadState('networkidle');

      const planSelector = page.locator('[data-bridge-plan-selector]');
      await expect(planSelector).toBeVisible({ timeout: MED_TIMEOUT });

      // Wait for loading to complete
      await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
        timeout: LONG_TIMEOUT,
      });

      // Find the free plan card and click "Select free plan"
      const selectBtn = page.locator(
        `[data-bridge-plan-card] button:has-text("Select free plan")`,
      ).first();
      await expect(selectBtn).toBeVisible({ timeout: MED_TIMEOUT });
      await selectBtn.click();

      // Wait for the plan selector to reload
      await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
        timeout: LONG_TIMEOUT,
      });

      // After selecting, the button for this plan should now say "Current plan"
      const currentPlanBtn = page
        .locator('[data-bridge-plan-card][data-current="true"] button')
        .first();
      await expect(currentPlanBtn).toBeVisible({ timeout: MED_TIMEOUT });
      const btnText = await currentPlanBtn.textContent();
      expect(btnText?.trim()).toContain('Current plan');
    } finally {
      await testDataClient.deletePlan(planKey).catch(() => {});
    }
  });

  test('switch from plan A to plan B via PlanSelector UI', async ({
    authenticatedPage,
    testUser,
    testDataClient,
  }) => {
    const page = authenticatedPage;
    const planAKey = `plan-a-e2e-${Date.now()}`;
    const planBKey = `plan-b-e2e-${Date.now()}`;

    try {
      // Create two free plans
      await testDataClient.createPlan({
        key: planAKey,
        name: 'Plan A',
        description: 'Plan A for switching test',
        prices: [{ amount: 0, currency: 'USD', recurrenceInterval: 'month' }],
      });
      await testDataClient.createPlan({
        key: planBKey,
        name: 'Plan B',
        description: 'Plan B for switching test',
        prices: [{ amount: 0, currency: 'USD', recurrenceInterval: 'month' }],
      });

      // Pre-select Plan A via the API so we start from a known state
      await testDataClient.setTenantPlan(testUser.tenantId, planAKey);

      await page.goto('/subscription');
      await page.waitForURL('**/subscription**', { timeout: MED_TIMEOUT });
      await page.waitForLoadState('networkidle');

      const planSelector = page.locator('[data-bridge-plan-selector]');
      await expect(planSelector).toBeVisible({ timeout: MED_TIMEOUT });
      await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
        timeout: LONG_TIMEOUT,
      });

      // Plan A should be the current plan
      const planACard = page.locator(`[data-bridge-plan-card][data-current="true"]`);
      await expect(planACard).toBeVisible({ timeout: MED_TIMEOUT });

      // Find Plan B's card and click its select button
      const planBCard = page.locator(`[data-bridge-plan-card][data-current="false"]`).first();
      await expect(planBCard).toBeVisible({ timeout: MED_TIMEOUT });
      const planBBtn = planBCard.locator('button').first();
      await expect(planBBtn).toBeVisible({ timeout: MED_TIMEOUT });
      await planBBtn.click();

      // Wait for reload
      await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
        timeout: LONG_TIMEOUT,
      });

      // Plan B should now be current
      const newCurrentCard = page.locator('[data-bridge-plan-card][data-current="true"]');
      await expect(newCurrentCard).toBeVisible({ timeout: MED_TIMEOUT });
    } finally {
      await testDataClient.deletePlan(planAKey).catch(() => {});
      await testDataClient.deletePlan(planBKey).catch(() => {});
    }
  });

  test('subscription state is reflected in plan selector data-state', async ({
    authenticatedPage,
    testUser,
    testDataClient,
  }) => {
    const page = authenticatedPage;

    await page.goto('/subscription');
    await page.waitForURL('**/subscription**', { timeout: MED_TIMEOUT });
    await page.waitForLoadState('networkidle');

    const planSelector = page.locator('[data-bridge-plan-selector]');
    await expect(planSelector).toBeVisible({ timeout: MED_TIMEOUT });
    await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
      timeout: LONG_TIMEOUT,
    });

    // data-state should be one of the valid states
    const state = await planSelector.getAttribute('data-state');
    expect([
      'idle',
      'select-plan',
      'active',
      'trial',
      'payment-failed',
      'setup-payments',
    ]).toContain(state);
  });

  test('set-plan via API is reflected in plan selector UI', async ({
    authenticatedPage,
    testUser,
    testDataClient,
  }) => {
    const page = authenticatedPage;
    const planKey = `reflect-e2e-${Date.now()}`;

    try {
      await testDataClient.createPlan({
        key: planKey,
        name: 'Reflect Plan',
        prices: [{ amount: 0, currency: 'USD', recurrenceInterval: 'month' }],
      });

      // Set plan directly via API
      await testDataClient.setTenantPlan(testUser.tenantId, planKey);

      await page.goto('/subscription');
      await page.waitForURL('**/subscription**', { timeout: MED_TIMEOUT });
      await page.waitForLoadState('networkidle');

      const planSelector = page.locator('[data-bridge-plan-selector]');
      await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
        timeout: LONG_TIMEOUT,
      });

      // The plan card for this plan should be marked as current
      const currentCard = page.locator('[data-bridge-plan-card][data-current="true"]');
      await expect(currentCard).toBeVisible({ timeout: MED_TIMEOUT });
    } finally {
      await testDataClient.deletePlan(planKey).catch(() => {});
    }
  });

  test('paid plan triggers Stripe checkout redirect', async ({
    authenticatedPage,
    testUser,
    testDataClient,
    envConfig,
  }) => {
    test.skip(!hasStripeKeys, 'STRIPE_TEST_PK / STRIPE_TEST_SK not set — skipping');
    const page = authenticatedPage;
    const planKey = `stripe-e2e-${Date.now()}`;

    try {
      // Enable Stripe on the app
      await testDataClient.configureApp({
        stripeEnabled: true,
        stripePublicKey: STRIPE_TEST_PK,
        stripeSecretKey: STRIPE_TEST_SK,
        currency: 'USD',
      });

      await testDataClient.createPlan({
        key: planKey,
        name: 'Stripe Pro',
        description: 'Paid plan for Stripe E2E',
        prices: [{ amount: 2900, currency: 'USD', recurrenceInterval: 'month' }],
      });

      await page.goto('/subscription');
      await page.waitForURL('**/subscription**', { timeout: MED_TIMEOUT });
      await page.waitForLoadState('networkidle');

      const planSelector = page.locator('[data-bridge-plan-selector]');
      await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
        timeout: LONG_TIMEOUT,
      });

      // Click the paid plan button — target the Stripe Pro card specifically
      const stripePlanCard = page.locator('[data-bridge-plan-card]').filter({ hasText: 'Stripe Pro' });
      await expect(stripePlanCard).toBeVisible({ timeout: MED_TIMEOUT });
      const paidBtn = stripePlanCard.locator('button').first();
      await expect(paidBtn).toBeVisible({ timeout: MED_TIMEOUT });
      await paidBtn.click();

      // Should be redirected to Stripe checkout (stripe.com domain)
      await page.waitForURL((url) => url.hostname.includes('stripe.com'), {
        timeout: LONG_TIMEOUT,
      });

      expect(page.url()).toContain('stripe.com');
    } finally {
      await testDataClient.deletePlan(planKey).catch(() => {});
      // Disable Stripe again
      await testDataClient.configureApp({ stripeEnabled: false }).catch(() => {});
    }
  });
});
