name: Build and Publish

on:
  push:
    branches: ["**"]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches: [main]

permissions:
  contents: write
  id-token: write

jobs:
  pipeline:
    uses: ./.github/workflows/publish.yml
    with:
      working-directory: bridge-svelte
      # Bun is the default toolchain, so no additional inputs are required
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
      docs-sync-key: ${{ secrets.DOCS_SYNC_KEY }}

